import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Program to convert an XML RSS (version 2.0) feed from a given URL into the
 * corresponding HTML output file.
 *
 * @author Put your name here
 *
 */
public final class RSSAggregator {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSAggregator() {
    }

    /**
     * Processes one XML RSS (version 2.0) feed from a given URL converting it
     * into the corresponding HTML output file.
     *
     * @param url
     *            the URL of the RSS feed
     * @param file
     *            the name of the HTML output file
     * @param out
     *            the output stream to report progress or errors
     * @updates out.content
     * @requires out.is_open
     * @ensures <pre>
     * [reads RSS feed from url, saves HTML document with table of news items
     *   to file, appends to out.content any needed messages]
     * </pre>
     */
    private static void processFeed(String url, String file, SimpleWriter out) {
        SimpleWriter rssOut = new SimpleWriter1L(file);

        XMLTree rss = new XMLTree1(url);
        XMLTree channel = rss.child(0);
        int title = getChildElement(channel, "title");

        out.println("<li><a href=\"" + file + "\">"
                + channel.child(title).child(0).label() + "</a></li>");

        outputHeader(channel, rssOut);
        outputFooter(rssOut);

        rssOut.close();
    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * <html> <head> <title>the channel tag title as the page title</title>
     * </head> <body> <h1>the page title inside a link to the <channel> link<h1>
     * <p>
     * the channel description
     * </p>
     * <table>
     * <tr>
     * <th>Date</th>
     * <th>Source</th>
     * <th>News</th>
     * </tr>
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        assert channel != null : "Violation of: channel is not null";
        assert out != null : "Violation of: out is not null";
        assert channel.isTag() && channel.label().equals("channel") : ""
                + "Violation of: the label root of channel is a <channel> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        int title = getChildElement(channel, "title");
        int link = getChildElement(channel, "link");
        int desc = getChildElement(channel, "description");

        out.println("<html>");
        out.println("<head>");
        out.println("<title>");
        out.println(channel.child(title).child(0).label());
        out.println("</title>");
        out.println("<body>");
        out.println("<h1>");
        out.println("<a href=\"" + channel.child(link).child(0) + "\">"
                + channel.child(title).child(0) + "</a>");
        out.println("</h1>");
        out.println("<p>");
        if (channel.child(desc).numberOfChildren() != 0
                && !channel.child(desc).child(0).label().equals("")) {
            out.println(channel.child(desc).child(0));
        } else {
            out.println("No description available");
        }
        out.println("</p>");
        out.println("<table border=1>");
        for (int i = 0; i < channel.numberOfChildren(); i++) {
            if (channel.child(i).label().equals("item")) {
                processItem(channel.child(i), out);
            }
        }
    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * </table> </body> </html>
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out) {
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";

        out.println("</table>");
        out.println("</body>");
        out.println("</html>");
    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first child of type tag of the {@code XMLTree} or
     *   -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {
        assert xml != null : "Violation of: xml is not null";
        assert tag != null : "Violation of: tag is not null";
        assert xml.isTag() : "Violation of: the label root of xml is a tag";

        for (int i = 0; i < xml.numberOfChildren(); i++) {
            if (xml.child(i).label().equals(tag)) {
                return i;
            }
        }
        return -1;
    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     *
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires <pre>
     * [the label of the root of item is an <item> tag] and out.is_open
     * </pre>
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */
    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item") : ""
        + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        int title = getChildElement(item, "title");
        int link = getChildElement(item, "link");
        int date = getChildElement(item, "pubDate");
        int source = getChildElement(item, "source");
        int desc = getChildElement(item, "description");
        out.println("<tr>");
        if (date != -1) {
            out.println("<td>" + item.child(date).child(0).label() + "</td>");
        } else {
            out.println("<td>No date available</td>");
        }
        if (source != -1) {
            out.println("<td>" + "<a href=\""
                    + item.child(source).attributeValue("url") + "\">"
                    + item.child(source).child(0).label() + "</a></td>");
        } else {
            out.println("<td>No source available</td>");
        }
        if (title != -1) {
            String t = item.child(title).child(0).label();
            if (!t.equals("")) {
                out.println("<td>" + "<a href=\""
                        + item.child(link).child(0).label() + "\">" + t
                        + "</a></td>");
            }
        } else if (desc != -1) {
            String d = item.child(desc).child(0).label();
            if (!d.equals("")) {
                out.println("<td>" + "<a href=\""
                        + item.child(link).child(0).label() + "\">" + d
                        + "</a></td>");
            }
        } else {
            out.println("<td>" + "<a href=\""
                    + item.child(link).child(0).label()
                    + "\">No title available</a></td>");
        }
        out.println("</tr>");
    }

    /**
     * Main method.
     *
     * @param args
     *            the command line arguments; unused here
     */
    public static void main(String[] args) {
        SimpleReader in = new SimpleReader1L();
        SimpleWriter fout = new SimpleWriter1L("index.html");
        SimpleWriter out = new SimpleWriter1L();

        fout.println("<html>");
        fout.println("<head>");
        fout.println("<title>Top Stories</title>");
        fout.println("</head>");
        fout.println("<body>");
        fout.println("<h2>Top Stories</h2>");
        fout.println("<ul>");

        XMLTree feed = new XMLTree1("feeds.xml");
        for (int i = 0; i < feed.numberOfChildren(); i++) {
            processFeed(feed.child(i).attributeValue("url"), feed.child(i)
                    .attributeValue("file"), fout);
        }

        fout.println("</ul>");
        fout.println("</body>");
        fout.println("</html>");

        in.close();
        out.close();
        fout.close();
    }
}